### ISSUE TITLE
It's not working in version 4.11.4

### ISSUE THREAD

**Issue by RodriguesCosta** [dominic-p/videojs-resolution-selector#19]
It's not working in version 4.11.4 you plan to upgrade your plugin?

**Comment by dominic-p** [comment]
Thanks for reporting this. I haven't tested with the latest version of Video.js. I'll try to carve out some time this week to get it working again. Do you know which browsers it's failing on? Did you get an error message? Do you have a test URL (or jsFiddle) we can look at?

**Comment by RodriguesCosta** [comment]
So I did not receive an error or the option to choose the resolution simply not appear ... I'm using the 4.9.1 version for now, I created a jsFiddle http://jsfiddle.net/758qhzeb/1/ in version 4.9.1 works perfectly you really did a great job

I apologize for any error English I am Brazilian I can not speak English'm using google translator

**Comment by dominic-p** [comment]
Thanks for putting the fiddle together. It seems to be working fine for me on 4.11.4. See: http://jsfiddle.net/758qhzeb/2/

The only thing I did was remove the `data-setup` attribute from your `<video>` tag. You can either initialize the video via js by calling the `videojs` function or by adding a `data-setup` attribute. It doesn't really matter which one you use, but you still need to enable the plugin, and it wasn't enabled in the `data-setup` in the original fiddle, so it never loaded.
