### ISSUE TITLE
Not working for RTMP streams?

### ISSUE THREAD

**Issue by koxle** [dominic-p/videojs-resolution-selector#20]
I copied the demo and it works using for vod(HTTP).

I tried to use for rtmp live stream.

<source src="rtmp://XXX.XXX.XXXo/live/livestream1080" type="rtmp/flv" data-res="1080" />
<source src="rtmp://XXX.XXX.XXXo/live/livestream720" type="rtmp/flv" data-res="720" />

Nothing was showed in the player.

Am I doing something wrong?

**Comment by dominic-p** [comment]
The Flash tech is not currently supported by the plugin. See issue #9 for a full discussion of why that is.
