### ISSUE TITLE
npm dependencies need a package.json

### ISSUE THREAD

**Issue by huster-zhangpeng** [dominic-p/videojs-resolution-selector#23]
npm dependencies need a package.json...

**Comment by dominic-p** [comment]
It's not a bad idea. I don't have the time to put one together right now, but pull requests are welcome.

**Comment by stopspazzing** [comment]
Also a bower package... you know I could probably spend a few minutes to do this today actually... Time to learn npm package.json and bower package requirements...

**Comment by stopspazzing** [comment]
I have not tested this yet, but believe it is up to par with requires for bower and npm: https://github.com/stopspazzing/videojs-resolution-selector
