### ISSUE TITLE
Can't see change resolution button

### ISSUE THREAD

**Issue by CKalnasy** [dominic-p/videojs-resolution-selector#24]
Everything works as it should except I cannot see the button text that changes the resolution. The button is there, but the text is not visible. This fiddle shows the issue: https://jsfiddle.net/5ptz30dL/. I tried using previous versions of video.js and this issue still persists. 

Looking at the HTML when I change resolutions, the text is changed accordingly. I can't figure out why the span tag showing the text isn't visible.

**Comment by CKalnasy** [comment]
I found out that the text of video.js control buttons are actually never shown. The absolute positioning causes this. I guess this kinda makes sense since we are probably supposed to add an image there instead.

**Comment by CKalnasy** [comment]
Ok, so add an image and it works. Maybe should point this out in the readme?

**Comment by dominic-p** [comment]
@CKalnasy, checkout the button-styles.css file. If you include those styles, the plain text will be visible (see [this fiddle](https://jsfiddle.net/gc27ddba/))
