### ISSUE TITLE
Resolution selector button unseen in Video.js using dominic-p/videojs-resolution-selector 

### ISSUE THREAD

**Issue by singhjan** [dominic-p/videojs-resolution-selector#25]
Recently I have added resolution selector ( dominic-p/videojs-resolution-selector - https://github.com/dominic-p/videojs-resolution-selector) and It is working . But resolution selector is not shown in menu bar but can be found when mouse keep near volume menu.

Tell me how to keep seeing resolution button in menu bar ?

I have CSS and i donot know why is is not working.

Pliz Check css:

@charset "utf-8";

/*
You are free to style the button however you wish. I plan to use
an icon from my site's own icon font to make it more visible. These
are just basic styles to make it look ok with plain text.
*/

/* Position the button */
.vjs-res-button {
float: right;
line-height: 3em;
}

/* Don't show hover effects on title */
ul li.vjs-menu-title.vjs-res-menu-title:hover {
cursor: default;
background-color: transparent;
color: #CCC;

-moz-box-shadow: none;
-webkit-box-shadow: none;
box-shadow: none;

}

/* Needed to keep text visible in video.js 4.9 */
.vjs-res-button .vjs-control-text {
width: auto;
height: auto;
clip: auto;
}

**Comment by dominic-p** [comment]
Could you put together a [jsFiddle](https://jsfiddle.net/) showing the problem? Do you have a link to an example that isn't working?

**Comment by singhjan** [comment]
http://videos.sunnyleone4u.com/2015/04/21/picasa-test/.

Resolution selector is shown when mouse cursor is near volume menu  and
without mouse cursor nowhere near the volume menu, it is unseen.

**Comment by dominic-p** [comment]
It looks like you are including the button-styles.css styles, but they are being overridden by the default Video.js styles. Be sure to include those styles _after_ the Video.js default styles.

**Comment by singhjan** [comment]
How to do it ? I have used free CDN version of video.js . I am running Video.js using <link href="http://vjs.zencdn.net/4.12/video-js.css" rel="stylesheet">
<script src="http://vjs.zencdn.net/4.12/video.js"></script>

**Comment by singhjan** [comment]
@dominic-p http://vjs.zencdn.net/4.12/video-js.css
http://vjs.zencdn.net/4.12/video.js

**Comment by dominic-p** [comment]
You will need to make sure you load the button-styles.css file after (lower down) in your code than when you load the video-js.css file.

This is not a support forum. I would recommend you do some reading on [how CSS overriding works](http://www.vanseodesign.com/css/css-specificity-inheritance-cascaade/). Or, you might try asking a question on [StackOverflow](http://stackoverflow.com/).
