### ISSUE TITLE
Passing videojs-resolution-selector setting to plugin does not work.

### ISSUE THREAD

**Issue by singhjan** [dominic-p/videojs-resolution-selector#26]
I have done what you described below but it is not working. I donot know why ? Wrong placed where setting pass or any mistake ? Where to pass the setting ? Help pliz.
Link: http://videos.sunnyleone4u.com/2015/04/21/picasa-test/

Optionally, you can pass some settings to the plugin:

videojs( '#my-video', { plugins : { resolutionSelector : {
    force_types : [ 'video/mp4', 'video/webm' ],
    default_res : "480"
} } } );

force_types is an array. The plugin will check each resolution to make sure there is a source of each type at that resolution.

**Comment by stopspazzing** [comment]
First off, you need to listen and understand this is not a support forum. Second, your last "issue" was locked and you were told where to go already to get support: https://github.com/dominic-p/videojs-resolution-selector/issues/25

3rd, turn off any caching plugin before testing
4th, button-styles.css isn't even in your head of your site.

If you still can't understand or have issues, pls go here: stackoverflow.com

**Comment by dominic-p** [comment]
@singhjan, I realize this stuff can be hard, but refusing to follow the rules of a forum is not going to get you anywhere. Please follow the advice that myself and @stopspazzing, have given you.

@stopspazzing, I appreciate the help in moderating this issue. Thanks.

**Comment by singhjan** [comment]
@dominic-p  Ok, I got what you said, As you are maker of this plugin, i ask that some setting is not working , So I ask what is the wrong . No one is better know than you as far as this plugin is concerned.

Besides, now i realised that there is no usage of " New Issue " button  in github.

Thnx for help
