### ISSUE TITLE
Using different video.js skins moves resolution-selector off of video controls bar

### ISSUE THREAD

**Issue by stopspazzing** [dominic-p/videojs-resolution-selector#27]
Tried using it with sublime skin and the selector gets moved to outside the video control bar (to far right). Is there a way this can be fixed via this plugin? Or would it be best to add issue on sublime?

**Comment by dominic-p** [comment]
Hmm, sounds like a CSS conflict of some kind. My instinct would be that it's an issue with sublime, but it's possible this plugin is doing something non-standard that's breaking the skin. Could you post a jsFiddle or a link to the issue?

**Comment by stopspazzing** [comment]
Sorry took so long, been busy.

http://jsfiddle.net/ksrwu6kx/

**Comment by dominic-p** [comment]
It almost looks like that skin doesn't support menu buttons at all. Strange. There does seem to be an [open issue](https://github.com/cabin/videojs-sublime-skin/issues/2) about support for a quality button, but that's been around for a while.

If they do ever get around to supporting it, you will probably want to remove the styles from button-styles.css as they will probably conflict. I'll go ahead and post your fiddle on that issue as I'm sure it will help.
