### ISSUE TITLE
npm package doesn't contain any useful files...

### ISSUE THREAD

**Issue by simbo** [dominic-p/videojs-resolution-selector#30]
As you are ignoring all files in your .npmignore and you don't have a files property in your package.json, your npm package is almost empty (except for license and readme)...

**Comment by dominic-p** [comment]
Hmm, that's kind of counter productive. :) I tweaked the .npmignore file, but I don't use npm a lot, so I'm not 100% if the new version is correct. Go ahead and test it, and let me know if it seems right.

**Comment by simbo** [comment]
Well, this ain't a theoretical issue - i already tested it. :)

Just add the following to your package.json:

```json
{
    "files": [
        "video-quality-selector.css",
        "video-quality-selector.js"
    ]
}
```

You don't have to add readme, license or package.json - they are included by default.

By using the `files` property in package.json, you can also remove your `.npmignore` competely, as only those files listed in package.json will be included. No ignores needed...

**Comment by dominic-p** [comment]
@simbo, thanks for the suggestion. Were you able to test it again after the changes I made to the `.npmignore` file?

**Comment by simbo** [comment]
Sorry for the delay...

Now with release of 1.6.1 all necessary files are included in the npm package.

But i wonder if it's necessary to set `video.js` as a dependency in package.json.
Sure this plugin is useless without `video.js` itself, but by defining it as dependency you have at least two installations of `video.js` within your project and the one within the `videojs-resolution-selector/node_modules` folder will probably never be used.

I would set `video.js` as a devDependency or remove it completely from package.json.

**Comment by dominic-p** [comment]
Thanks for the tip. I looked through a few of the other plugins listed on the Wiki, and most don't seem to declare video.js as dependency. So, I went ahead and removed it from package.json.
