### ISSUE TITLE
Video playing from the beginning on quality change

### ISSUE THREAD

**Issue by vitalyiegorov** [dominic-p/videojs-resolution-selector#33]
Is this normal behaviour, maybe we can add something to continue playing from the same place on quality change? @dominic-p

**Comment by dominic-p** [comment]
It should pickup where you left off on a quality change. Do you have an example that's showing the problem? Maybe you can put together a [jsFiddle](http://jsfiddle.net/) so we can take a look?

**Comment by vitalyiegorov** [comment]
@dominic-p http://ellotv.bigdig.com.ua/en/video/dzhigan-holodnoe-serdce
maybe this is due to videojs-vast-plugin which is showing ads on quality change?

**Comment by dominic-p** [comment]
The example video you linked seems to be working fine to me (video resumes where it left off on resolution changes). Did you make any changes to your code or other plugins?

**Comment by vitalyiegorov** [comment]
Yes, we have changed ad source, and there are now add actually right now, when ad would be added I will write here

**Comment by dominic-p** [comment]
Ok, I'll go ahead and close this for now then as it seems like possibly an issue with another plugin. Feel free to post here though if/when you have more details.
