### ISSUE TITLE
resolution selector to my site having video.js

### ISSUE THREAD

**Issue by raidpipe** [dominic-p/videojs-resolution-selector#34]
can any one just give me a brief how to add the resolution selector to my site having video.js player the site url is www.reurl.in/ab8647946 i just want a HD and NON-HD play if possible . also please tell me do i need to provide diffrent video resolution src or the same video will be converted to the desired rate. hd is about 720px and non-hd is 360px. please help its imp . Thankyou .

**Comment by dominic-p** [comment]
@raidpipe installation instructions are available on [the readme](https://github.com/dominic-p/videojs-resolution-selector/blob/master/README.md). Read it carefully, and look at [the example file](https://github.com/dominic-p/videojs-resolution-selector/blob/1.6.2/example.html). As I've said before, this is not a support forum. Please don't post support requests here.
